use std::{
    collections::HashMap,
    hash::Hash,
    io::{Read, Write},
    os::{fd::AsRawFd, unix::process::CommandExt},
    process::Stdio,
    str::FromStr,
};

use anyhow::{Context, anyhow};
use serde::{Deserialize, Serialize};
use sysinfo::System;

use crate::{
    config::WorkerConfig,
    libc::{Fork, Signal, dup2, fork, setsid, signal, stop_pg, waitpid},
    pty::{self},
    pty_server::PtyServer,
};

/// Project deserialized from config file
#[derive(Deserialize, Serialize, Clone, Debug, Eq, PartialEq, Default)]
pub struct Project {
    pub name: String,
    pub command: Vec<String>,
    pub cwd: String,
    pub display: Option<String>,
    pub stop_signal: Option<Signal>,
    pub envs: Option<HashMap<String, String>>,
    pub group: Option<Vec<String>>,
    pub dependencies: Option<Vec<String>>,
}

/// Project with process id
#[derive(Deserialize, Serialize, Clone, Debug, Eq, PartialEq)]
pub struct RunningProject {
    pub name: String,
    pub command: Vec<String>,
    pub cwd: String,
    pub display: Option<String>,
    pub stop_signal: Option<Signal>,
    pub envs: Option<HashMap<String, String>>,
    pub group: Option<Vec<String>>,
    pub dependencies: Option<Vec<String>>,
    pub pid: i32,
}

impl Project {
    pub fn from_cmd(name: String, cmd: String) -> Self {
        Project {
            name,
            command: vec!["sh".to_string(), "-c".to_string(), cmd],
            cwd: std::env::current_dir()
                .unwrap()
                .to_string_lossy()
                .to_string(),
            display: None,
            stop_signal: None,
            envs: None,
            group: None,
            dependencies: None,
        }
    }

    pub fn start(&self, config: &WorkerConfig) -> Result<(), anyhow::Error> {
        self.start_dependencies(config)?;

        let sock_path = config.sock_file(self);
        // Capture terminal size before forking — after fork, stdio is /dev/null
        let (rows, cols) = pty::get_terminal_size();

        match fork().expect("Couldn't fork") {
            Fork::Parent(p) => {
                waitpid(p).unwrap();
            }
            Fork::Child => {
                // Pipe so shepherd can signal readiness before intermediate exits
                let (mut pipe_r, mut pipe_w) = std::io::pipe().expect("Failed to create pipe");

                match fork().expect("Couldn't fork shepherd") {
                    Fork::Parent(_) => {
                        // Intermediate: wait for shepherd to be ready, then exit
                        drop(pipe_w);
                        let _ = pipe_r.read(&mut [0u8; 1]);
                        drop(pipe_r);
                        std::process::exit(0);
                    }
                    Fork::Child => {
                        // Shepherd process
                        drop(pipe_r);
                        // Redirect inherited stdio to /dev/null so we don't
                        // hold open any pipes from the parent (e.g. test harness).
                        if let Ok(devnull) = std::fs::OpenOptions::new()
                            .read(true)
                            .write(true)
                            .open("/dev/null")
                        {
                            dup2(devnull.as_raw_fd(), libc::STDIN_FILENO);
                            dup2(devnull.as_raw_fd(), libc::STDOUT_FILENO);
                            dup2(devnull.as_raw_fd(), libc::STDERR_FILENO);
                        }

                        let sid = setsid().expect("Couldn't setsid");
                        let mut pty = pty::Pty::open(rows, cols).expect("Failed to open PTY");

                        // Make the PTY slave the controlling terminal of this session
                        unsafe {
                            libc::ioctl(
                                pty.slave.as_raw_fd(),
                                libc::TIOCSCTTY as libc::c_ulong,
                                0i32,
                            );
                        }

                        config
                            .store_state(sid, self)
                            .expect("Failed to store state");

                        match fork().expect("Couldn't fork command") {
                            Fork::Parent(child_pid) => {
                                drop(pty.slave);
                                // Ignore signals generated by the PTY line discipline
                                signal(libc::SIGINT, libc::SIG_IGN);
                                signal(libc::SIGQUIT, libc::SIG_IGN);
                                signal(libc::SIGTSTP, libc::SIG_IGN);
                                let server = PtyServer::bind(&sock_path)?;
                                // Signal readiness to intermediate
                                let _ = pipe_w.write_all(&[1u8]);
                                drop(pipe_w);
                                server.event_loop(&mut pty.master, child_pid);
                                std::process::exit(0);
                            }
                            Fork::Child => {
                                drop(pty.master);
                                drop(pipe_w);
                                dup2(pty.slave.as_raw_fd(), libc::STDIN_FILENO);
                                dup2(pty.slave.as_raw_fd(), libc::STDOUT_FILENO);
                                dup2(pty.slave.as_raw_fd(), libc::STDERR_FILENO);
                                drop(pty.slave);

                                let _ = std::process::Command::new(&self.command[0])
                                    .args(&self.command[1..])
                                    .envs(self.envs.clone().unwrap_or_default())
                                    .current_dir(&self.cwd)
                                    .exec();
                            }
                        }
                    }
                }
            }
        };

        Ok(())
    }

    pub fn start_dependencies(&self, config: &WorkerConfig) -> Result<(), anyhow::Error> {
        if let Some(ref deps) = self.dependencies {
            for dep in deps {
                let project = Project::from_str(dep)?;
                if !project.is_running(config)? {
                    project.start(config)?;
                }
            }
        }
        Ok(())
    }

    pub fn run(&self) -> Result<(), anyhow::Error> {
        let _ = std::process::Command::new(&self.command[0])
            .args(&self.command[1..])
            .envs(self.envs.clone().unwrap_or_default())
            .current_dir(&self.cwd)
            .stdin(Stdio::null())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .spawn()?
            .wait();
        Ok(())
    }

    pub fn is_running(&self, config: &WorkerConfig) -> Result<bool, anyhow::Error> {
        Ok(config.running()?.iter().any(|it| it.name == self.name))
    }
}

impl RunningProject {
    pub fn stop(&self) -> Result<(), anyhow::Error> {
        let signal = self.stop_signal.as_ref().unwrap_or(&Signal::SIGINT);
        stop_pg(self.pid, signal).map_err(|e| anyhow!("Error trying to stop project: {e}"))
    }
}

impl From<RunningProject> for Project {
    fn from(value: RunningProject) -> Self {
        Self {
            name: value.name,
            command: value.command,
            cwd: value.cwd,
            display: value.display,
            stop_signal: value.stop_signal,
            envs: value.envs,
            group: value.group,
            dependencies: value.dependencies,
        }
    }
}

pub trait WorkerProject {
    fn name(&self) -> &str;
}

impl Hash for Project {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.name.hash(state)
    }
}

impl Hash for RunningProject {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.name.hash(state)
    }
}

macro_rules! impl_display {
    ($project:tt) => {
        impl std::fmt::Display for $project {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                if let Some(ref display) = self.display {
                    write!(f, "{} ({})", display, self.name)
                } else {
                    write!(f, "{}", self.name)
                }
            }
        }
    };
}

macro_rules! impl_worker_project {
    ($project:tt) => {
        impl WorkerProject for $project {
            fn name(&self) -> &str {
                &self.name
            }
        }
    };
}

impl_display!(Project);
impl_display!(RunningProject);

impl_worker_project!(Project);
impl_worker_project!(RunningProject);

impl FromStr for Project {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let config = WorkerConfig::new()?;
        let projects: Vec<String> = config.projects.iter().map(|p| p.name.clone()).collect();

        config
            .projects
            .into_iter()
            .find(|it| it.name == s)
            .with_context(|| format!("Valid projects are {:#?}", projects))
    }
}

impl FromStr for RunningProject {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let config = WorkerConfig::new()?;
        let project = config
            .get_state(s)?
            .ok_or_else(|| anyhow!("Project {} is not running or does not exist", s))?;

        let mut sys = System::new();
        sys.refresh_all();
        let has_processes_running = sys.processes().iter().any(|(_, p)| {
            p.session_id()
                .is_some_and(|session_id| session_id.as_u32() == project.pid as u32)
        });

        if !has_processes_running {
            return Err(anyhow!("{} is not running", project));
        }

        Ok(project)
    }
}
